version: "3"

services:
  alertmanager-dingtalk:
    image: llybood/alertmanager-dingtalk:latest
    container_name: alertmanager-dingtalk
    volumes:
      - ./config/config.yaml:/app/alertmanager-dingtalk/config/config.yaml
      - ./template/template.tmpl:/app/alertmanager-dingtalk/template/template.tmpl
    ports:
      - "8111:8111"
    restart: always
